# Generated by Django 4.0.3 on 2022-03-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='sniffer',
            name='device_name',
            field=models.CharField(max_length=125),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
