# Generated by Django 2.2.26 on 2022-02-04 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220203_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='beacon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='app.BeaconDevice'),
        ),
    ]
