# Generated by Django 4.0.3 on 2022-03-16 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20220203_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('description', models.TextField(default='')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sniffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.TextField(max_length=64)),
                ('serial_code', models.SlugField(max_length=19)),
                ('is_master', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sniffers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='beacondevice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='beacondevice',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='uuid',
        ),
        migrations.AddField(
            model_name='beacondevice',
            name='bc_uuid',
            field=models.UUIDField(default=uuid.UUID('0b48fcc9-1544-424d-b475-c8ee790fd35a'), unique=True, verbose_name='Broadcast UUID'),
        ),
        migrations.AddField(
            model_name='beacondevice',
            name='device_name',
            field=models.TextField(default='Beacon Device', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='beacondevice',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beacondevice',
            name='model',
            field=models.CharField(choices=[('DEV', 'Development Model'), ('IB', 'iBeacon')], default='DEV', max_length=125),
        ),
        migrations.AddField(
            model_name='beacondevice',
            name='owner',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='beacons', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('beacon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.beacondevice')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.location')),
                ('sniffer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.sniffer')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='sniffer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sniffer'),
        ),
    ]
